"""empty message

Revision ID: 3c9671643eae
Revises: 3cd01487c45c
Create Date: 2023-11-18 09:35:38.320696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9671643eae'
down_revision: Union[str, None] = '3cd01487c45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmtt',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('person', sa.String(length=63), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=127), nullable=True),
    sa.Column('stir', sa.String(length=10), nullable=True),
    sa.Column('tg_user_id', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('stir', sa.String(length=10), nullable=True),
    sa.Column('tg_user_id', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.drop_table('dmtt')
    # ### end Alembic commands ###
