"""empty message

Revision ID: 6e7bafe915fb
Revises: 485e880b3642
Create Date: 2023-11-22 08:56:13.133714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e7bafe915fb'
down_revision: Union[str, None] = '485e880b3642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('stir', sa.String(length=10), nullable=True),
    sa.Column('tg_user_id', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('organization')
    op.drop_constraint('season_products_ibfk_1', 'season_products', type_='foreignkey')
    op.create_foreign_key(None, 'season_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'season_products', type_='foreignkey')
    op.create_foreign_key('season_products_ibfk_1', 'season_products', 'products', ['product_id'], ['id'])
    op.create_table('organization',
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('stir', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('tg_user_id', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('company')
    # ### end Alembic commands ###
