"""migarte name

Revision ID: 7676ebf06e91
Revises: 6acc8eaed691
Create Date: 2023-11-18 11:19:37.687110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7676ebf06e91'
down_revision: Union[str, None] = '6acc8eaed691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'is_active')
    # ### end Alembic commands ###
