"""empty message

Revision ID: 86f7df951f07
Revises: b07f08c347f4
Create Date: 2023-11-22 09:06:57.365475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f7df951f07'
down_revision: Union[str, None] = 'b07f08c347f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('dmtt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'connection', 'dmtt', ['dmtt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connection', type_='foreignkey')
    op.drop_column('connection', 'dmtt_id')
    # ### end Alembic commands ###
