"""migarte name

Revision ID: a7c02abfe2b9
Revises: 06d49ad2892b
Create Date: 2023-11-19 21:44:36.280804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c02abfe2b9'
down_revision: Union[str, None] = '06d49ad2892b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmtt', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmtt', 'is_active')
    # ### end Alembic commands ###
