"""empty message

Revision ID: bf08997539fb
Revises: 124d2d46f64c
Create Date: 2023-11-23 19:54:36.289767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf08997539fb'
down_revision: Union[str, None] = '124d2d46f64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_products')
    op.add_column('products', sa.Column('winter', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('spring', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('summer', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('autumn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'autumn')
    op.drop_column('products', 'summer')
    op.drop_column('products', 'spring')
    op.drop_column('products', 'winter')
    op.create_table('season_products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('season', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='season_products_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
