"""empty message

Revision ID: c31dbe637b1e
Revises: 8462be03746f
Create Date: 2024-01-12 08:24:47.912818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31dbe637b1e'
down_revision: Union[str, None] = '8462be03746f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmtt_persons',
    sa.Column('dmtt_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=31), nullable=True),
    sa.Column('last_name', sa.String(length=31), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('tg_user_id', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dmtt_id'], ['dmtt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dmtt', sa.Column('child_count', sa.Integer(), nullable=True))
    op.drop_column('dmtt', 'tg_user_id')
    op.drop_column('dmtt', 'person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmtt', sa.Column('person', sa.VARCHAR(length=63), nullable=True))
    op.add_column('dmtt', sa.Column('tg_user_id', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('dmtt', 'child_count')
    op.drop_table('dmtt_persons')
    # ### end Alembic commands ###
